server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: is-lab1

  jpa:
    generate-ddl: ${SPRING_JPA_GENERATE_DDL:true}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        jdbc.lob.non_contextual_creation: ${SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NON_CONTEXTUAL_CREATION:true}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:15432/studs}
    username: ${SPRING_DATASOURCE_USERNAME:s333291}
    password: ${SPRING_DATASOURCE_PASSWORD:qwerty12345}

application:
  security:
    jwt:
      secret-key: ${APPLICATION_SECURITY_JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: ${APPLICATION_SECURITY_EXPIRATION:86400000} # a day
    unique-password-constraint: ${APPLICATION_SECURITY_UNIQUE_PASSWORD_CONSTRAINT:true}

springdoc:
  api-docs:
    enabled: ${SPRINGDOC_API_DOCS_ENABLED:true}
  swagger-ui:
    enabled: ${SPRINGDOC_SWAGGER_UI_ENABLED:true}
